### ISSUE TITLE
Availability of crowd counting pre-trained models

### ISSUE THREAD

**Issue by rachillesf** [gjy3035/C-3-Framework#7]
Are there available pre-trained models for the whole network, for testing without the need for any training?

Thanks

**Comment by gjy3035** [comment]
I have provided the pretrained models on GCC_rd in readme. You can download them from the relevant link.
However, I do not still plan to provide the model on other datasets, because the training only takes several hours on 1080Ti. 
If you indeed need them, I may plan to provide them in future. Thanks for your attention!
